name: 'Client Build'
on:
  release:
    types:
      - published
      - released
jobs:
  Standalone:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.4f1
        targetPlatform:
          # - StandaloneOSX
          # - StandaloneWindows64
          - StandaloneLinux64
          # - Android

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch configuration
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ env.GITHUB_REF }}
          file: cognito.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Place configuration
        run: mv cognito.json Assets/cognito.json

      - name: Cache
        uses: actions/cache@v1.1.0
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-

      - name: Build
        uses: webbertakken/unity-builder@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
