name: 'Backend Deployment'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lambdas:
    name: 'Lambda build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Lambdas
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.2
        with:
          go-version: 1.15

      - name: Tests
        run: go test ./...

      - name: Build
        run: |
          mkdir -p build
          go build -o build/sqs-forward sqs-forward/main.go

      - name: Debug
        run: ls -laR

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sqs-forward
          path: build/sqs-forward

  backend:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: [lambdas]

    defaults:
      run:
        shell: bash
        working-directory: Backend

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: sqs-forward

    - name: Package lambda
      run: zip -jD sqs-forward.zip sqs-forward

    - name: List files
      run: ls -laR

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
